# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Random Walk Metropolis sampler (Laplace Distribution)
#' @description A MCMC sampler using Rcpp
#' @param sigma the scaling parameter for increment distribution
#' @param x0 the initial value
#' @param N the sample size you want
#' @return a random sample of size \code{N}
#' @useDynLib SC19092
#' @examples
#' \dontrun{
#' Crw <- rwcpp(1, 0, 2000)
#' chain <- Crw[[1]]
#' plot(1:1000,chain[1:1000],type="l",xlab = "Scaling parameter = 1",ylab="Chain",ylim=range(chain))
#' }
#' @export
rwcpp <- function(sigma, x0, N) {
    .Call('_SC19092_rwcpp', PACKAGE = 'SC19092', sigma, x0, N)
}

